# Generated by Django 5.1.4 on 2025-01-16 12:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True,
                always_update=True,
                editable=False,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
