# Generated by Django 5.1.4 on 2025-02-04 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tag",
            field=models.CharField(
                blank=True, max_length=555, null=True, verbose_name="Blog Tag"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
