# Generated by Django 5.1.4 on 2025-02-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_created_at_alter_blog_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default=1, upload_to="blog_images/", verbose_name="Blog Image"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="image_caption",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Image Caption"
            ),
        ),
        migrations.DeleteModel(
            name="BlogImage",
        ),
    ]
