# Generated by Django 5.1.4 on 2025-02-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_image_blog_image_caption_delete_blogimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_images/",
                verbose_name="Blog Image",
            ),
        ),
    ]
