# Generated by Django 5.1.4 on 2025-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
