# Generated by Django 5.1.4 on 2025-01-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_designation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_by",
        ),
    ]
