# Generated by Django 5.1.4 on 2025-02-04 05:50

import autoslug.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="alias",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="projects",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True,
                always_update=True,
                default="20240204-202212",
                editable=False,
                populate_from="title",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projects",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="projects",
            name="user_ip",
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="alias",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="review",
            name="role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True,
                always_update=True,
                default=1,
                editable=False,
                populate_from="title",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="review",
            name="user_ip",
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
