# Generated by Django 5.1.4 on 2025-02-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_projects_alias_projects_created_at_projects_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="category",
            field=models.CharField(default="apps", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projects",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
