# Generated by Django 5.1.4 on 2025-02-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_projects_category_alter_projects_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="alias",
        ),
        migrations.RemoveField(
            model_name="review",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="review",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="review",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user_ip",
        ),
    ]
