# Generated by Django 5.1.4 on 2025-08-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_projects_project_image_projectimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="alias",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="user_ip",
        ),
    ]
