# Generated by Django 5.1.4 on 2025-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_purpose",
            field=models.TextField(blank=True, null=True),
        ),
    ]
