# Generated by Django 5.1.4 on 2025-08-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_projectimage_alias_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="projects",
            name="category",
        ),
        migrations.AddField(
            model_name="projects",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIVE", "LIVE"),
                    ("ON_GOING", "ON_GOING"),
                    ("COMPLETED", "COMPLETED"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="categories",
            field=models.ManyToManyField(blank=True, to="home.category"),
        ),
    ]
