# Generated by Django 5.1.4 on 2025-08-29 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_category_remove_projects_category_projects_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="duration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="technologies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("PYTHON", "Python"),
                        ("JAVA", "Java"),
                        ("C", "C"),
                        ("CPP", "C++"),
                        ("CSHARP", "C#"),
                        ("JAVASCRIPT", "JavaScript"),
                        ("TYPESCRIPT", "TypeScript"),
                        ("PHP", "PHP"),
                        ("RUBY", "Ruby"),
                        ("SWIFT", "Swift"),
                        ("KOTLIN", "Kotlin"),
                        ("GO", "Go"),
                        ("RUST", "Rust"),
                        ("SCALA", "Scala"),
                        ("PERL", "Perl"),
                        ("DART", "Dart"),
                        ("DJANGO", "Django"),
                        ("FLASK", "Flask"),
                        ("FASTAPI", "FastAPI"),
                        ("SPRING", "Spring Boot"),
                        ("EXPRESS", "Express.js"),
                        ("LARAVEL", "Laravel"),
                        ("RAILS", "Ruby on Rails"),
                        ("ANGULAR", "Angular"),
                        ("REACT", "React.js"),
                        ("VUE", "Vue.js"),
                        ("NEXTJS", "Next.js"),
                        ("NUXTJS", "Nuxt.js"),
                        ("MYSQL", "MySQL"),
                        ("POSTGRESQL", "PostgreSQL"),
                        ("SQLITE", "SQLite"),
                        ("MONGODB", "MongoDB"),
                        ("REDIS", "Redis"),
                        ("ORACLE", "Oracle Database"),
                        ("MSSQL", "Microsoft SQL Server"),
                        ("CASSANDRA", "Cassandra"),
                        ("COUCHDB", "CouchDB"),
                        ("FIREBASE", "Firebase"),
                        ("AWS", "Amazon Web Services"),
                        ("AZURE", "Microsoft Azure"),
                        ("GCP", "Google Cloud Platform"),
                        ("HEROKU", "Heroku"),
                        ("DIGITALOCEAN", "DigitalOcean"),
                        ("DOCKER", "Docker"),
                        ("KUBERNETES", "Kubernetes"),
                        ("ANDROID", "Android"),
                        ("IOS", "iOS"),
                        ("FLUTTER", "Flutter"),
                        ("REACT_NATIVE", "React Native"),
                        ("TENSORFLOW", "TensorFlow"),
                        ("PYTORCH", "PyTorch"),
                        ("SCIKIT", "Scikit-learn"),
                        ("TRANSFORMERS", "HuggingFace Transformers"),
                        ("GIT", "Git"),
                        ("GITHUB", "GitHub"),
                        ("GITLAB", "GitLab"),
                        ("BITBUCKET", "Bitbucket"),
                        ("JENKINS", "Jenkins"),
                        ("CI_CD", "CI/CD"),
                    ],
                    max_length=50,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
