# Generated by Django 5.1.4 on 2025-09-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_technology_remove_projects_technologies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technology",
            name="name",
        ),
    ]
