# Generated by Django 5.1.4 on 2025-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_remove_technology_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="duration",
            field=models.CharField(
                choices=[
                    ("8", "8"),
                    ("10", "10"),
                    ("12", "12"),
                    ("14", "14"),
                    ("16", "16"),
                    ("18", "18"),
                    ("20", "20"),
                    ("22", "22"),
                    ("24", "24"),
                    ("26", "26"),
                    ("28", "28"),
                    ("30", "30"),
                    ("32", "32"),
                ],
                default="8",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIVE", "LIVE"),
                    ("ON_GOING", "OnGoing"),
                    ("COMPLETED", "Completed"),
                    ("INCOMPLETE", "Incomplete"),
                    ("CANCELED", "Canceled"),
                    ("ON_HOLD", "OnHold"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
