# Generated by Django 5.1.4 on 2025-09-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_contact_email_alter_contact_name"),
        ("home", "0012_alter_projects_duration_alter_projects_status"),
    ]

    operations = []
