# Generated by Django 5.1.4 on 2025-09-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_merge_20250918_1519"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="projects",
            name="categories",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "INFORMATIONAL_OR_MARKETING_WEBSITE",
                        "Informational or Marketing website",
                    ),
                    ("PORTFOLIO_AND_RESUME_WEBSITE", "Portfolio & Resume website"),
                    (
                        "BROCHURE_OR_LANDING_PAGE_WEBSITE",
                        "Brochure or Landing Page website",
                    ),
                    (
                        "PERSONAL_BLOG_OR_KNOWLEDGE_HUB",
                        "Personal Blog or Knowledge Hub",
                    ),
                    ("E_COMMERCE_WEBSITE", "E-Commerce website"),
                    ("MARKETPLACE_PLATFORM", "Marketplace platform"),
                    (
                        "SUBSCRIPTION_OR_MEMBERSHIP_WEBSITE",
                        "Subscription or Membership website",
                    ),
                    (
                        "WEB_APPLICATION",
                        "Web Application (SaaS, Dashboards, CRMs, ERPs)",
                    ),
                    ("SOCIAL_NETWORK", "Social Network website"),
                    ("FORUM_OR_DISCUSSION_BOARD", "Forum or Discussion Board"),
                    ("COMMUNITY_QA_WEBSITE", "Community Q&A website"),
                    (
                        "DATING_OR_HOBBY_COMMUNITY_WEBSITE",
                        "Dating or Hobby Community website",
                    ),
                    (
                        "MEDIA_AND_ENTERTAINMENT_WEBSITE",
                        "Media & Entertainment website (Streaming, News, Magazines, Galleries)",
                    ),
                    (
                        "PODCAST_OR_AUDIO_VIDEO_PLATFORM",
                        "Podcast / Audio / Video platform",
                    ),
                    (
                        "EDUCATIONAL_WEBSITE",
                        "Educational website (e-learning, LMS, Courses, Schools)",
                    ),
                    (
                        "KNOWLEDGE_BASE_OR_DOCUMENTATION_SITE",
                        "Knowledge Base or Documentation site",
                    ),
                    ("NONPROFIT_OR_NGO_WEBSITE", "Nonprofit / NGO website"),
                    ("GOVERNMENT_OR_MUNICIPAL_PORTAL", "Government / Municipal portal"),
                    (
                        "FUNDRAISING_OR_DONATION_WEBSITE",
                        "Fundraising / Donation website",
                    ),
                    ("JOB_BOARD", "Job Board website"),
                    ("CLASSIFIED_ADS_WEBSITE", "Classified Ads website"),
                    (
                        "TRAVEL_BOOKING_OR_COMPARISON_WEBSITE",
                        "Travel Booking / Comparison website",
                    ),
                    ("LOCAL_BUSINESS_DIRECTORY", "Local Business Directory"),
                    (
                        "CUSTOM_OR_EXPERIMENTAL_WEBSITE",
                        "Custom or Experimental website (Interactive, VR / AR, Games)",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
