from django.db import models
from django.utils.translation import gettext_lazy as _


class StatusChoices(models.TextChoices):
    ACTIVE = "ACTIVE", _("Active")
    INACTIVE = "INACTIVE", _("Inactive")



class UserTypeChoices(models.TextChoices):
    ADMIN = "ADMIN", _("Admin")
    MODERATOR = "MODERATOR", _("Moderator")


class ProjectStatusChoices(models.TextChoices):
    LIVE = "LIVE", _("LIVE")
    ON_GOING = "ON_GOING", _("OnGoing")
    COMPLETED = "COMPLETED", _("Completed")
    INCOMPLETE = "INCOMPLETE", _("Incomplete")
    CANCELED = "CANCELED", _("Canceled")
    ON_HOLD = "ON_HOLD", _("OnHold")


class TechChoices(models.TextChoices):
    PYTHON = "PYTHON", _("Python")
    JAVA = "JAVA", _("Java")
    C = "C", _("C")
    CPP = "CPP", _("C++")
    CSHARP = "CSHARP", _("C#")
    JAVASCRIPT = "JAVASCRIPT", _("JavaScript")
    TYPESCRIPT = "TYPESCRIPT", _("TypeScript")
    PHP = "PHP", _("PHP")
    RUBY = "RUBY", _("Ruby")
    SWIFT = "SWIFT", _("Swift")
    KOTLIN = "KOTLIN", _("Kotlin")
    GO = "GO", _("Go")
    RUST = "RUST", _("Rust")
    SCALA = "SCALA", _("Scala")
    PERL = "PERL", _("Perl")
    DART = "DART", _("Dart")
    DJANGO = "DJANGO", _("Django")
    FLASK = "FLASK", _("Flask")
    FASTAPI = "FASTAPI", _("FastAPI")
    SPRING = "SPRING", _("Spring Boot")
    EXPRESS = "EXPRESS", _("Express.js")
    LARAVEL = "LARAVEL", _("Laravel")
    RAILS = "RAILS", _("Ruby on Rails")
    ANGULAR = "ANGULAR", _("Angular")
    REACT = "REACT", _("React.js")
    VUE = "VUE", _("Vue.js")
    NEXTJS = "NEXTJS", _("Next.js")
    NUXTJS = "NUXTJS", _("Nuxt.js")
    MYSQL = "MYSQL", _("MySQL")
    POSTGRESQL = "POSTGRESQL", _("PostgreSQL")
    SQLITE = "SQLITE", _("SQLite")
    MONGODB = "MONGODB", _("MongoDB")
    REDIS = "REDIS", _("Redis")
    ORACLE = "ORACLE", _("Oracle Database")
    MSSQL = "MSSQL", _("Microsoft SQL Server")
    CASSANDRA = "CASSANDRA", _("Cassandra")
    COUCHDB = "COUCHDB", _("CouchDB")
    FIREBASE = "FIREBASE", _("Firebase")
    AWS = "AWS", _("Amazon Web Services")
    AZURE = "AZURE", _("Microsoft Azure")
    GCP = "GCP", _("Google Cloud Platform")
    HEROKU = "HEROKU", _("Heroku")
    DIGITALOCEAN = "DIGITALOCEAN", _("DigitalOcean")
    DOCKER = "DOCKER", _("Docker")
    KUBERNETES = "KUBERNETES", _("Kubernetes")
    ANDROID = "ANDROID", _("Android")
    IOS = "IOS", _("iOS")
    FLUTTER = "FLUTTER", _("Flutter")
    REACT_NATIVE = "REACT_NATIVE", _("React Native")
    TENSORFLOW = "TENSORFLOW", _("TensorFlow")
    PYTORCH = "PYTORCH", _("PyTorch")
    SCIKIT = "SCIKIT", _("Scikit-learn")
    TRANSFORMERS = "TRANSFORMERS", _("HuggingFace Transformers")
    GIT = "GIT", _("Git")
    GITHUB = "GITHUB", _("GitHub")
    GITLAB = "GITLAB", _("GitLab")
    BITBUCKET = "BITBUCKET", _("Bitbucket")
    JENKINS = "JENKINS", _("Jenkins")
    CI_CD = "CI_CD", _("CI/CD")

class DurationsChoice(models.TextChoices):
    W8 = "8", _("8")
    W10 = "10", _("10")
    W12 = "12", _("12")
    W14 = "14", _("14")
    W16 = "16", _("16")
    W18 = "18", _("18")
    W20 = "20", _("20")
    W22 = "22", _("22")
    W24 = "24", _("24")
    W26 = "26", _("26")
    W28 = "28", _("28")
    W30 = "30", _("30")
    W32 = "32", _("32")

class CategoriesChoices(models.TextChoices):
    INFORMATIONAL_OR_MARKETING_WEBSITE = "INFORMATIONAL_OR_MARKETING_WEBSITE", _("Informational or Marketing website")
    PORTFOLIO_AND_RESUME_WEBSITE = "PORTFOLIO_AND_RESUME_WEBSITE", _("Portfolio & Resume website")
    BROCHURE_OR_LANDING_PAGE_WEBSITE = "BROCHURE_OR_LANDING_PAGE_WEBSITE", _("Brochure or Landing Page website")
    PERSONAL_BLOG_OR_KNOWLEDGE_HUB = "PERSONAL_BLOG_OR_KNOWLEDGE_HUB", _("Personal Blog or Knowledge Hub")
    E_COMMERCE_WEBSITE = "E_COMMERCE_WEBSITE", _("E-Commerce website")
    MARKETPLACE_PLATFORM = "MARKETPLACE_PLATFORM", _("Marketplace platform")
    SUBSCRIPTION_OR_MEMBERSHIP_WEBSITE = "SUBSCRIPTION_OR_MEMBERSHIP_WEBSITE", _("Subscription or Membership website")
    WEB_APPLICATION = "WEB_APPLICATION", _("Web Application (SaaS, Dashboards, CRMs, ERPs)")
    SOCIAL_NETWORK = "SOCIAL_NETWORK", _("Social Network website")
    FORUM_OR_DISCUSSION_BOARD = "FORUM_OR_DISCUSSION_BOARD", _("Forum or Discussion Board")
    COMMUNITY_QA_WEBSITE = "COMMUNITY_QA_WEBSITE", _("Community Q&A website")
    DATING_OR_HOBBY_COMMUNITY_WEBSITE = "DATING_OR_HOBBY_COMMUNITY_WEBSITE", _("Dating or Hobby Community website")
    MEDIA_AND_ENTERTAINMENT_WEBSITE = "MEDIA_AND_ENTERTAINMENT_WEBSITE", _("Media & Entertainment website (Streaming, News, Magazines, Galleries)")
    PODCAST_OR_AUDIO_VIDEO_PLATFORM = "PODCAST_OR_AUDIO_VIDEO_PLATFORM", _("Podcast / Audio / Video platform")
    EDUCATIONAL_WEBSITE = "EDUCATIONAL_WEBSITE", _("Educational website (e-learning, LMS, Courses, Schools)")
    KNOWLEDGE_BASE_OR_DOCUMENTATION_SITE = "KNOWLEDGE_BASE_OR_DOCUMENTATION_SITE", _("Knowledge Base or Documentation site")
    NONPROFIT_OR_NGO_WEBSITE = "NONPROFIT_OR_NGO_WEBSITE", _("Nonprofit / NGO website")
    GOVERNMENT_OR_MUNICIPAL_PORTAL = "GOVERNMENT_OR_MUNICIPAL_PORTAL", _("Government / Municipal portal")
    FUNDRAISING_OR_DONATION_WEBSITE = "FUNDRAISING_OR_DONATION_WEBSITE", _("Fundraising / Donation website")
    JOB_BOARD = "JOB_BOARD", _("Job Board website")
    CLASSIFIED_ADS_WEBSITE = "CLASSIFIED_ADS_WEBSITE", _("Classified Ads website")
    TRAVEL_BOOKING_OR_COMPARISON_WEBSITE = "TRAVEL_BOOKING_OR_COMPARISON_WEBSITE", _("Travel Booking / Comparison website")
    LOCAL_BUSINESS_DIRECTORY = "LOCAL_BUSINESS_DIRECTORY", _("Local Business Directory")
    CUSTOM_OR_EXPERIMENTAL_WEBSITE = "CUSTOM_OR_EXPERIMENTAL_WEBSITE", _("Custom or Experimental website (Interactive, VR / AR, Games)")
